version: "3.7"
services:
  client-api:
    container_name: "client-api"
#    image: client-api:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - "8080:8080"
    environment:
      INIT_DATABASE: false
      INIT_DATABASE_DUMP: /app/clients.csv
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
    depends_on:
      mongo_db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/clients.csv:/app/clients.csv
  mongo_db:
    container_name: "mongo_db"
    image: "mongo:4.4.17"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
#    environment:
#      :
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/clientsdb --quiet
      interval: 1s
      timeout: 10s
      retries: 10

    command: "mongod --quiet --logpath /dev/null"