version: "3.7"
services:
  client-api:
    container_name: "client-api"
    image: client-api:0.0.2
    restart: "on-failure"
    environment:
      INIT_DATABASE: true
      INIT_DATABASE_DUMP: /app/humanz-ex-users.csv
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
    #    healthcheck:
    #      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
    #      interval: 25s
    #      timeout: 10s
    #      retries: 3
    depends_on:
      mongo_db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/humanz-ex-users.csv:/app/humanz-ex-users.csv
  mongo_db:
    container_name: "mongo_db"
    image: "mongo:4.4.17"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
#    environment:
#      :
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/humanzdb --quiet
      interval: 1s
      timeout: 10s
      retries: 10

    command: "mongod --quiet --logpath /dev/null"